services:
  - type: web
    name: legacy-academy-tracking
    env: python
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn attendance_system.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: True
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: ADMIN_URL
        value: "secure-admin-panel/"
      - key: DATABASE_URL
        fromDatabase:
          name: legacy-academy-db
          property: connectionString

databases:
  - name: legacy-academy-db
    databaseName: legacy_academy_db
    user: legacy_user
    plan: free