# Generated by Django 4.2.17 on 2025-07-17 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Employee number must be uppercase letters and numbers')]),
        ),
    ]
